version: '3'

services:
  smart_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx
    command: nginx -g "daemon off;"
    container_name: smart_frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8181:80"
    volumes:
      - ./html/smart-vue/dist:/usr/share/nginx/html:ro
    networks:
      - smart-network

networks:
  smart-network:
    driver: bridge

volumes:
  dist:
